services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: scoreteam-postgres-dev
    environment:
      POSTGRES_DB: scoreteam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./server/src/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - scoreteam-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scoreteam"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
    driver: local

networks:
  scoreteam-network-dev:
    driver: bridge
