services:
  postgres:
    image: postgres:15-alpine
    container_name: scoreteam-postgres-prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-scoreteam}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
      - ./init-migrations.sh:/docker-entrypoint-initdb.d/init-migrations.sh
      - ./backups:/backups
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - postgres-network-prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-scoreteam}"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    # Production security settings
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp
      - /var/run/postgresql

volumes:
  postgres_data_prod:
    driver: local

networks:
  postgres-network-prod:
    driver: bridge
