services:
  postgres:
    image: postgres:15-alpine
    container_name: scoreteam-postgres-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-scoreteam}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
      - ./init-migrations.sh:/docker-entrypoint-initdb.d/init-migrations.sh
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - postgres-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-scoreteam_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data_dev:
    driver: local

networks:
  postgres-network-dev:
    driver: bridge
